#!/bin/sh
script_dir_link=$(dirname "$(readlink "$0")")
APPDIR="${script_dir_link}/../webapp"

CP="${APPDIR}/WEB-INF/classes"
for i in `ls ${APPDIR}/WEB-INF/lib` ; do CP="${CP}:${APPDIR}/WEB-INF/lib/${i}" ; done
for i in ${script_dir_link}/../ext/*.jar ; do XCP="${XCP}:${i}" ; done
echo "Extra jars: ${XCP}"
CP="${CP}:${XCP}"

java -cp ${CP} br.com.devx.scenery.Main $*
